backup:
  destination: ~/2021-09-andy-mac-refresh
  listings:
    applications: /Applications
    code: ~/Code 
  mappings:
    - from: '~'
      to: home
      files:
        - .aws
        - .config
        - .vscode
        - bin
        - Code/ansible-php
        - .gitconfig
        - .bash_profile
        - .git-completion.bash
        - .git-prompt.sh
        - .gitconfig
        - .ssh/config
        - .npmrc  
        - Code/homestead/Homestead.yaml
  app-config: 
    from: ~/Code
    to: app-config
    files:
      include: 
        - .env
    directories:
      exclude:
        - target
        - node_modules
        - vendor
      include:
        - config*
        - .idea  
   

