common:
  destination: ~/andy-mac-refresh
  listings:
    applications: /Applications
    code: ~/Code 
  mappings:
    - from: '~'
      to: home
      files:
        - .gitconfig
        - .bash_profile
        - .git-completion.bash
        - .git-prompt
        - .gitconfig
        - .ssh/config
    - from: 'Library/Application Support/MySQL/Workbench'
      to: mysql
      files:
        - connections.xml
        - server_instances.xml
secure: 
  destination: ~/andy-mac-refresh-secure
  app-config: 
    from: ~/Code
    to: app-config
    files:
      include: 
        - .env
    directories:
      exclude:
        - target
        - node_modules
        - vendor
      include:
        - config
        - .idea  
  mappings:
    - from: '~'
      to: home
      files:
        .npmrc    

